---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
- node_modules/**/*
require:
- rails
domains: []
diagnostics: true
reporters:
- rubocop
- require_not_found
plugins:
- runtime
require_paths: []
max_files: 5000
