tap "amberframework/amber"
tap "denisidoro/tools"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "joshuaclayton/formulae"
tap "luckyframework/lucky"
tap "neovim/neovim"
tap "universal-ctags/universal-ctags"
cask "adoptopenjdk8"
cask "xquartz"
brew "icu4c"
brew "boost"
brew "docbook"
brew "source-highlight"
brew "asciidoc"
brew "openssl@1.1"
brew "readline", link: true
brew "sqlite"
brew "xz"
brew "asciinema"
brew "aspell"
brew "augeas"
brew "autoconf"
brew "automake"
brew "bash"
brew "bash-completion"
brew "bat"
brew "broot"
brew "ghc"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "libffi"
brew "pcre"
brew "python"
brew "glib"
brew "cairo"
brew "mpfr"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "dialog"
brew "diff-so-fancy"
brew "docbook-xsl"
brew "docker-completion"
brew "dos2unix"
brew "elasticsearch", restart_service: true
brew "exa"
brew "faac"
brew "fd"
brew "libogg"
brew "flac"
brew "fribidi"
brew "giflib"
brew "libtasn1"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "jpeg"
brew "webp"
brew "libvpx"
brew "rtmpdump"
brew "sdl2"
brew "snappy"
brew "tesseract"
brew "x264"
brew "xvid"
brew "ffmpeg", link: false
brew "fortune"
brew "fswatch"
brew "fzf"
brew "fzy"
brew "isl"
brew "libmpc"
brew "gcc"
brew "gd"
brew "szip"
brew "hdf5"
brew "libxml2"
brew "proj"
brew "libpq"
brew "libtool"
brew "netcdf"
brew "nspr"
brew "nss"
brew "numpy"
brew "qt"
brew "poppler"
brew "unixodbc"
brew "geckodriver"
brew "git"
brew "git-lfs"
brew "git-quick-stats"
brew "glew"
brew "glm"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "pkg-config"
brew "gobject-introspection"
brew "gts"
brew "graphviz"
brew "hadolint"
brew "hexyl"
brew "hivemind"
brew "ncurses"
brew "htop"
brew "hyperfine"
brew "libde265"
brew "libheif"
brew "libomp"
brew "imagemagick", link: false
brew "imagemagick@6", link: true
brew "jemalloc"
brew "oniguruma"
brew "jq"
brew "kompose"
brew "less"
brew "libav"
brew "libev"
brew "libsass"
brew "libssh2"
brew "unibilium"
brew "libtermkey"
brew "libusb-compat"
brew "libuv"
brew "libvterm"
brew "libxkbcommon"
brew "libxslt"
brew "libyaml"
brew "swig"
brew "llvm"
brew "lnav"
brew "lolcat"
brew "lsd"
brew "luarocks"
brew "mailhog", restart_service: true
brew "mas"
brew "msgpack"
brew "protobuf"
brew "mysql", restart_service: true
brew "neovim", args: ["HEAD"]
brew "node"
brew "node-sass"
brew "opam"
brew "optipng"
brew "tmux"
brew "overmind"
brew "packer"
brew "pango"
brew "pgcli"
brew "plantuml"
brew "pngcrush"
brew "postgresql", restart_service: true
brew "postgis"
brew "prettyping"
brew "proselint"
brew "pth"
brew "python@2"
brew "ranger"
brew "redis", restart_service: true
brew "ripgrep"
brew "ruby"
brew "rust"
brew "sdl2_image"
brew "selenium-server-standalone", restart_service: true
brew "shellcheck"
brew "siege"
brew "sphinx"
brew "termbox"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tig"
brew "tree"
brew "unison"
brew "v8"
brew "vim"
brew "watchman"
brew "wget"
brew "wrk"
brew "wxmac"
brew "yajl"
brew "zlib"
brew "zsh"
brew "denisidoro/tools/navi", args: ["HEAD"]
brew "heroku/brew/heroku"
brew "joshuaclayton/formulae/unused"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "acorn"
cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "bartender"
cask "bettertouchtool"
cask "betterzip"
cask "camtasia"
cask "chromedriver"
cask "colorsnapper"
cask "contexts"
cask "daisydisk"
cask "dash"
cask "devonthink"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "fission"
cask "font-roboto"
cask "gitter"
cask "google-chrome"
cask "hazel"
cask "hyper"
cask "insomnia"
cask "iterm2"
cask "java"
cask "kaleidoscope"
cask "keyboard-maestro"
cask "lepton"
cask "macdown"
cask "moom"
cask "notion"
cask "path-finder"
cask "pdfkey-pro"
cask "pdfpenpro"
cask "pgadmin4"
cask "scapple"
cask "sip"
cask "slack"
cask "snagit"
cask "sublime-text"
cask "tableplus"
cask "visual-studio-code"
cask "wkhtmltopdf"
cask "zeplin"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "EasyRes", id: 688211836
mas "Folder Factory", id: 521419726
mas "GAget", id: 968487158
mas "GarageBand", id: 682658836
mas "Gemini 2", id: 1090488118
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Ringer", id: 402437824
mas "Screenium 3", id: 921553264
mas "VisualDiffer", id: 412386481
mas "Xcode", id: 497799835
