---
include:
- "**/*.rb"
exclude:
- "**/*.jay"
- ".bundle/**/*"
- bower_components/**/*
- coverage/**/*
- integration_spec/**/*
- log/**/*
- node_modules/**/*
- spec/**/*
- test/**/*
- tmp/**/*
- vendor/**/*
require:
- rails
- actioncable
- actionmailer
- actionpack
- actionview
- activejob
- activemodel
- activerecord
- activestorage
- activesupport
domains: []
diagnostics: true
log: true
reporters:
- require_not_found
# - runtime
require_paths: []
max_files: 10000
