-- References:
-- https://gitlab.com/Iron_E/dotfiles
-- https://github.com/LunarVim/Neovim-from-scratch
require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.commands'
require 'user.colorscheme'
require 'user.catppuccin'
require 'user.nvim-lastplace'
require 'user.nvim-autopairs'
require 'user.todo-comments'
require 'user.comment'
require 'user.indent-blankline'
require 'user.barbar'
require 'user.neoscroll'
require 'user.nvim-tree'
require 'user.lualine'
require 'user.nvim-colorizer'
